"""Add index to email in user table

Revision ID: 526e494a94bd
Revises: 6c9f33159894
Create Date: 2019-10-09 22:25:15.965425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526e494a94bd'
down_revision = '6c9f33159894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_portfolio_user_email'), 'portfolio_user', ['email'], unique=True)
    op.drop_constraint('portfolio_user_email_key', 'portfolio_user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('portfolio_user_email_key', 'portfolio_user', ['email'])
    op.drop_index(op.f('ix_portfolio_user_email'), table_name='portfolio_user')
    # ### end Alembic commands ###
