"""Add user_id to StockTransaction and make user_id not nullable on InvestmentAccount

Revision ID: 6c1cb8371ec5
Revises: 526e494a94bd
Create Date: 2019-10-11 21:35:12.546446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c1cb8371ec5'
down_revision = '526e494a94bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('investment_account', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('stock_transaction', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'stock_transaction', 'portfolio_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_transaction', type_='foreignkey')
    op.drop_column('stock_transaction', 'user_id')
    op.alter_column('investment_account', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
