"""Add user table

Revision ID: 6c9f33159894
Revises: feba5e2758ba
Create Date: 2019-10-07 21:31:13.766937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c9f33159894'
down_revision = 'feba5e2758ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('investment_account', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'investment_account', 'portfolio_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'investment_account', type_='foreignkey')
    op.drop_column('investment_account', 'user_id')
    op.drop_table('portfolio_user')
    # ### end Alembic commands ###
