"""Add more transaction types

Revision ID: c88703e3f670
Revises: dbb54787775a
Create Date: 2019-10-29 21:31:39.602387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c88703e3f670'
down_revision = 'dbb54787775a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
