"""Add trade_date column to StockTransaction table

Revision ID: cd0b2ace96a5
Revises: 6c1cb8371ec5
Create Date: 2019-10-13 23:38:56.374204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd0b2ace96a5'
down_revision = '6c1cb8371ec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_transaction', sa.Column('trade_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_transaction', 'trade_date')
    # ### end Alembic commands ###
